export const MONSTERS = [
  {
    name: "Goblin",
    icon: "👺",
    hd: 6,
    lvlRange: [1, 4],
    habitat: ["DANGER", "FOREST"],
    xp: 50,
    gold: [2, 8],
    loot: ["Small Dagger", "Moldy Bread"],
  },
  {
    name: "Dire Wolf",
    icon: "🐺",
    hd: 8,
    lvlRange: [1, 5],
    habitat: ["FOREST", "DANGER", "GRASS"],
    xp: 100,
    gold: [0, 5],
    loot: ["Wolf Pelt", "Fang Necklace"],
  },
  {
    name: "Skeleton",
    icon: "💀",
    hd: 8,
    lvlRange: [1, 4],
    habitat: ["DANGER"],
    xp: 100,
    gold: [1, 10],
    loot: ["Old Sword", "Bone Fragment"],
  },
  {
    name: "Bandit",
    icon: "🗡️",
    hd: 8,
    lvlRange: [2, 6],
    habitat: ["GRASS", "DANGER", "SAND"],
    xp: 125,
    gold: [5, 20],
    loot: ["Leather Armor", "Short Sword", "Coin Purse"],
  },
  {
    name: "Giant Spider",
    icon: "🕷️",
    hd: 8,
    lvlRange: [2, 5],
    habitat: ["FOREST"],
    xp: 200,
    gold: [0, 4],
    loot: ["Spider Silk", "Venom Gland"],
  },
  {
    name: "Orc Warrior",
    icon: "👹",
    hd: 10,
    lvlRange: [3, 7],
    habitat: ["DANGER", "MOUNTAIN"],
    xp: 250,
    gold: [3, 15],
    loot: ["Battle Axe", "Orcish Shield"],
  },
  {
    name: "Cave Troll",
    icon: "🧌",
    hd: 12,
    lvlRange: [4, 8],
    habitat: ["MOUNTAIN", "DANGER"],
    xp: 450,
    gold: [10, 30],
    loot: ["Troll Hide", "Club of Smashing"],
  },
  {
    name: "Shadow Wraith",
    icon: "👻",
    hd: 8,
    lvlRange: [5, 10],
    habitat: ["DANGER"],
    xp: 500,
    gold: [5, 25],
    loot: ["Shadow Essence", "Soul Shard"],
  },
  {
    name: "Ogre",
    icon: "👾",
    hd: 12,
    lvlRange: [4, 9],
    habitat: ["MOUNTAIN", "DANGER"],
    xp: 400,
    gold: [8, 24],
    loot: ["Giant Club", "Hide Armor"],
  },
  {
    name: "Wyvern",
    icon: "🐉",
    hd: 12,
    lvlRange: [7, 12],
    habitat: ["MOUNTAIN", "DANGER"],
    xp: 900,
    gold: [20, 60],
    loot: ["Dragon Scale", "Wyvern Talon"],
  },
  {
    name: "Lich",
    icon: "🧟",
    hd: 10,
    lvlRange: [8, 15],
    habitat: ["DANGER"],
    xp: 1500,
    gold: [30, 80],
    loot: ["Lich Phylactery", "Spellbook", "Death Robe"],
  },
  {
  name: "Magma Brute",
  icon: "🔥",
  hd: 16,
  lvlRange: [10, 16],
  habitat: ["VOLCANO", "OBSIDIAN"],
  xp: 2200,
  gold: [80, 150],
  loot: ["Molten Core", "Obsidian Axe", "Fireforged Armor"],
},
{
  name: "Ash Revenant",
  icon: "🩸",
  hd: 14,
  lvlRange: [9, 14],
  habitat: ["VOLCANO"],
  xp: 1800,
  gold: [60, 120],
  loot: ["Ashen Cloak", "Cursed Ember"],
},
  {
  name: "Eldritch Watcher",
  icon: "👁️",
  hd: 15,
  lvlRange: [10, 18],
  habitat: ["ELDRITCH"],
  xp: 2600,
  gold: [100, 180],
  loot: ["Watcher Eye", "Reality Fracture Shard"],
},
{
  name: "Whispering Horror",
  icon: "🕳️",
  hd: 17,
  lvlRange: [12, 20],
  habitat: ["ELDRITCH", "BLIGHT"],
  xp: 3200,
  gold: [120, 220],
  loot: ["Sanity Tether", "Mindshard Relic"],
},
  {
  name: "Blight Hulk",
  icon: "☣️",
  hd: 18,
  lvlRange: [11, 18],
  habitat: ["BLIGHT"],
  xp: 2800,
  gold: [90, 170],
  loot: ["Blighted Plate", "Rotting Heart"],
},
{
  name: "Plague Herald",
  icon: "🦠",
  hd: 16,
  lvlRange: [12, 19],
  habitat: ["BLIGHT", "SWAMP"],
  xp: 3000,
  gold: [100, 200],
  loot: ["Herald Sigil", "Virulent Tome"],
},
  {
  name: "Jungle Devourer",
  icon: "🐍",
  hd: 15,
  lvlRange: [9, 15],
  habitat: ["JUNGLE"],
  xp: 1900,
  gold: [70, 140],
  loot: ["Venom Core", "Scaled Hide"],
},
{
  name: "Ancient Apex",
  icon: "🦖",
  hd: 20,
  lvlRange: [14, 22],
  habitat: ["JUNGLE"],
  xp: 4200,
  gold: [150, 300],
  loot: ["Apex Fang", "Primeval Relic"],
},
];
